baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Thom - Blog'
theme = 'terminal'

[params]
    readMore = "More"
    fullWidthTheme = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'